USE BD_Gymnastique;
GO

INSERT INTO Appareil.Agre (Nom) VALUES 
('Sol'),
('Cheval d’arçons'), 
('Anneaux'), 
('Saut de cheval'),
('Barres parallèles'),
('Barre fixe')
GO

INSERT INTO Performances.Gymnaste (Nom, Prenom, DateNaissance, Pays, NBMedailles)
VALUES 
('Hashimoto', 'Daiki', '20010807', 'Japon', 12),
('Zhang', 'Boheng', '20000119', 'Chine', 10),
('Kovtun', 'Illia', '20030810', 'Ukraine', 8),
('Fraser', 'Joe', '19981206', 'Royaume-Uni', 7),
('Jarman', 'Jake', '2001-12-03', 'Royaume-Uni', 6),
('Yulo', 'Carlos Edriel', '20000216', 'Philippines', 5),
('Asil', 'Adem', '19990221', 'Turquie', 5),
('McClenaghan', 'Rhys', '19990721', 'Irlande', 4),
('Dolci', 'Félix', '20020505', 'Canada', 4),
('Karimi', 'Milad', '19990721', 'Kazakhstan', 4),
('Kaya', 'Kazuma', '19961110', 'Japon', 3),
('Dauser', 'Lukas', '19930615', 'Allemagne', 3),
('Mészáros', 'Krisztofer', '20000101', 'Hongrie', 3),
('Abbadini', 'Yumin', '20010412', 'Italie', 2),
('Seifert', 'Noe', '19980915', 'Suisse', 2),
('Langenegger', 'Florian', '19991120', 'Suisse', 2),
('Richard', 'Fred', '20030523', 'États-Unis', 2),
('Hong', 'Asher', '20040323', 'États-Unis', 2),
('Juda', 'Paul', '20010716', 'États-Unis', 2),
('Cournoyer', 'René', '19970425', 'Canada', 2);
GO

INSERT INTO Performances.Competition (Nom, [Date], Lieu)
VALUES 
('Jeux Olympiques 2024', '20240726', 'Paris'),
('Championnats du Monde 2023', '20231002', 'Anvers'),
('Coupe du Monde Doha 2023', '20230301', 'Doha'),
('Coupe du Monde Cottbus 2023', '20230221', 'Cottbus'),
('Championnats Européens 2023', '20230411', 'Antalya'),
('Coupe du Monde Baku 2023', '20230309', 'Bakou'),
('Jeux Asiatiques 2023', '20230923', 'Hangzhou'),
('Championnats Panaméricains 2023', '20230514', 'Medellín'),
('Championnats Nationaux USA 2023', '20230818', 'San José'),
('Championnats Nationaux Japon 2023', '20230622', 'Tokyo'),
('Championnats Nationaux Royaume-Uni 2023', '20230715', 'Liverpool'),
('Championnats Nationaux Allemagne 2023', '20230801', 'Berlin'),
('Championnats Nationaux Chine 2023', '20230905', 'Pékin'),
('Championnats Nationaux France 2023', '20230610', 'Paris'),
('Championnats Nationaux Brésil 2023', '20230730', 'Rio de Janeiro');
GO

INSERT INTO Performances.Performance (NoteObtenue, GymnasteID, CompetitionID, AgresID, MouvementID)
VALUES 
(15.2, 1, 1, 1, NULL), (14.8, 1, 2, 2, NULL),
(16.5, 2, 3, 3, NULL), (15.9, 2, 4, 4, NULL),
(14.7, 3, 5, 5, NULL), (14.3, 3, 6, 6, NULL),
(15.8, 4, 7, 1, NULL), (15.2, 4, 8, 2, NULL),
(16.1, 5, 9, 3, NULL), (15.5, 5, 10, 4, NULL),
(14.9, 6, 11, 5, NULL), (14.4, 6, 12, 6, NULL),
(15.6, 7, 13, 1, NULL), (15.0, 7, 14, 2, NULL),
(15.3, 8, 15, 3, NULL), (14.9, 8, 1, 4, NULL),
(14.5, 9, 2, 5, NULL), (14.1, 9, 3, 6, NULL),
(15.7, 10, 4, 1, NULL), (15.2, 10, 5, 2, NULL),
(14.8, 11, 6, 3, NULL), (14.3, 11, 7, 4, NULL),
(15.9, 12, 8, 5, NULL), (15.4, 12, 9, 6, NULL),
(14.6, 13, 10, 1, NULL), (14.2, 13, 11, 2, NULL),
(15.5, 14, 12, 3, NULL), (15.1, 14, 13, 4, NULL),
(14.7, 15, 14, 5, NULL), (14.3, 15, 15, 6, NULL),
(15.8, 16, 1, 1, NULL), (15.4, 16, 2, 2, NULL),
(14.9, 17, 3, 3, NULL), (14.5, 17, 4, 4, NULL),
(15.6, 18, 5, 5, NULL), (15.2, 18, 6, 6, NULL),
(14.8, 19, 7, 1, NULL), (14.4, 19, 8, 2, NULL),
(15.7, 20, 9, 3, NULL), (15.3, 20, 10, 4, NULL);
GO

INSERT INTO Appareil.Mouvement (Nom, Difficulte, Valeur, [Description], AgreID) VALUES 
--Mouvements pour le sol
(NULL, 'A', 0.1, 'From hdst. lower to L-sit orstrad. L-sit (2 s.)', 1),
(NULL, 'A', 0.1, 'From stand, Swiss press to hdst. (2 s.).', 1),
(NULL, 'A', 0.1, 'Rock to hdst. from prone position (2 s.).', 1),
(NULL, 'A', 0.1, 'Handstand (2 s.). ', 1),
(NULL, 'A', 0.1, 'Planche, legs straddle (2 s.).', 1),
(NULL, 'A', 0.1, '½ or 1/1 turn in handstand or to handstand.', 1),
(NULL, 'A', 0.1, 'From L-sit, etc., turn over bwd. to stand. ', 1),
(NULL, 'A', 0.1, 'Forward walkover.', 1),
(NULL, 'A', 0.1, 'Cross or side split (stop required).', 1),
(NULL, 'A', 0.1, 'Any standing scale (2 s.).', 1),
(NULL, 'A', 0.1, 'Jump bwd. to front support.', 1),
(NULL, 'A', 0.1, 'Butterfly', 1),
(NULL, 'A', 0.1, '1 circle or flair.', 1),
(NULL, 'A', 0.1, 'Flair with ½ spindle.', 1),
(NULL, 'A', 0.1, 'Russian wendeswing with 360° or 540°', 1),
(NULL, 'A', 0.1, 'Roll bwd. through hdst. with ½ t', 1),
(NULL, 'A', 0.1, 'Forward handspring or flyspring.', 1),
(NULL, 'A', 0.1, 'Dive roll.', 1),
(NULL, 'A', 0.1, 'Salto fwd. tucked or piked, also with ½ t.', 1),
(NULL, 'A', 0.1, 'Salto backwards tucked or piked.', 1),
(NULL, 'A', 0.1, 'Salto backwards tucked or piked w. ½ t. or Arabian tucked or piked.', 1),
(NULL, 'A', 0.1, 'Back handspring.', 1),
(NULL, 'A', 0.1, 'Jump bwd. with ½ t. to roll fwd.', 1),
(NULL, 'B', 0.2, 'V-sit (2 s.).', 1),
(NULL, 'B', 0.2, 'Pikedbody,str. armorstr.body,bent armpress to hdst. with legs together (2 s.).', 1),
(NULL, 'B', 0.2, 'Pressfrom split, L-sitstrad. orfrontsup. (2 s.).', 1),
(NULL, 'B', 0.2, 'PressorlowerorswingtoJapanesehdst.(2s.).', 1),
(NULL, 'B', 0.2, 'From straddled planche (2 s.) press hdst. (2 s.).', 1),
(NULL, 'B', 0.2, 'Endo roll to handstand (2 s.).', 1),
(NULL, 'B', 0.2, 'Anystandingscalewith180° straddle,no hand hold (2 s.).', 1),
('Endo', 'B', 0.2, 'Jump bwd. with pike-stretch or with 1/1 turn to front support', 1),
('Tong Fei', 'B', 0.2, 'Butterfly with 1/1 twist fwd. or bwd.', 1),
(NULL, 'B', 0.2, 'Circles or flair to handstand.', 1),
(NULL, 'B', 0.2, 'Lower from hdst. to flair or circle.', 1),
(NULL, 'B', 0.2, 'Flair with 1/1 spindle (in 2 circles).', 1),
(NULL, 'B', 0.2, 'Flair with ½ spindle to handstand.', 1),
(NULL, 'B', 0.2, 'Russian wendeswing with 720° or 900°.', 1),
(NULL, 'B', 0.2, 'Roll bwd. with hop 1/1 t. through hdst.', 1),
(NULL, 'B', 0.2, 'Salto fwd. straight, also with ½ t.', 1),
(NULL, 'B', 0.2, 'Salto fwd. t. or p. to front support.', 1),
(NULL, 'B', 0.2, 'Salto backwards str. or Tempo salto bwd.', 1),
(NULL, 'B', 0.2, 'Salto backwards str. w. ½ t. or or 1/1 t.', 1),
(NULL, 'B', 0.2, 'Salto fwd. tucked with 1/1 t., also with 3/2 t.', 1),
(NULL, 'B', 0.2, 'Salto backwards str. w. 1/1 t.', 1),
(NULL, 'B', 0.2, 'Salto backwards tucked w. 3/2 t.', 1),
('Manna', 'C', 0.3, 'V-sit with legs horizontal. (2 s.)', 1),
(NULL, 'C', 0.3, 'V-sit (2 s) and press to hdst. (2 s.). Also final phase with straddle.', 1),
(NULL, 'C', 0.3, 'From split press to Japanese handstand (2 s.).', 1),
(NULL, 'C', 0.3, 'Planche (2 s.). / Swallow (2 s.).', 1),
(NULL, 'C', 0.3, 'Endo roll piked to handstand legs together (2 s.).', 1),
(NULL, 'C', 0.3, 'Butterfly with 2/1 twist.', 1),
('Gogoladze', 'C', 0.3, 'Flair or circle to hdst. continue to flair or circle.', 1),
(NULL, 'C', 0.3, 'Flairwith >270 spindle (in 2 circles) directly to handstand.', 1),
('Fedorchenko', 'C', 0.3, 'Russian wendeswing with 1080° or more.', 1),
(NULL, 'C', 0.3, 'Double salto bwd. tucked.', 1),
(NULL, 'C', 0.3, 'Salto fwd. str. with 1/1 t., also with 3/2 t.', 1),
(NULL, 'C', 0.3, 'Salto bwd. str. with 3/2 t. or 2/1 t', 1),
(NULL, 'D', 0.4, 'Manna (2 s.) and press to hdst. (2 s.). Also final phase with straddle.', 1),
(NULL, 'D', 0.4, 'From Manna (2 s.), turn over (dislocation) to handstand (2 s.).', 1),
(NULL, 'D', 0.4, 'From Planche 2 s. press handstand (2 s.).', 1),
('Alvariño', 'D', 0.4, 'FromSwallow 2 s.presstoJapanesehdst.(2s.)', 1),
(NULL, 'D', 0.4, 'Flairhoppingwith360°t.bwd.thr.hdstandback to flair (2 hops).', 1),
(NULL, 'D', 0.4, 'Flair with > 270º spindle (in 2 circles) directly to handstand and continue to circle or flair.', 1),
('Morandi', 'D', 0.4, 'Handspring salto fwd. tuck.', 1),
(NULL, 'D', 0.4, 'Double salto fwd. tucked', 1),
(NULL, 'D', 0.4, 'Double salto fwd. tucked with ½ t.', 1),
('Deferr', 'D', 0.4, 'Jump fwd. with ½ t. to dbl. salto bwd. Tuck', 1),
('Tsukahara', 'D', 0.4, 'Salto bwd. with 1/1 t. and salto bwd.', 1),
(NULL, 'D', 0.4, 'Arabian jump bwd. to double salto fwd tucked', 1),
(NULL, 'D', 0.4, 'Arabian jump bwd. to double salto fwd tucked with ½ t.', 1),
(NULL, 'D', 0.4, 'Double salto bwd. piked.', 1),
(NULL, 'D', 0.4, 'Salto fwd. str. with 2/1 t.', 1),
(NULL, 'D', 0.4, 'Salto bwd. str. with 5/2 t.', 1),
(NULL, 'D', 0.4, 'Salto bwd. str. with 3/1 t.', 1),
(NULL, 'E', 0.5, 'Double salto fwd. piked', 1),
(NULL, 'E', 0.5, 'Double salto fwd. piked with ½ t.', 1),
(NULL, 'E', 0.5, '5. Double salto bwd. tucked with 2/1 t.', 1),
(NULL, 'E', 0.5, 'Double salto bwd t. with 3/2 t', 1),
('Korosteljev', 'E', 0.5, 'r salto bwd. str. 3/2 to fwd. salto tucked', 1),
(NULL, 'E', 0.5, 'Arabian jump bwd. to double salto fwd piked', 1),
(NULL, 'E', 0.5, 'Arabian jump bwd. to double salto fwd piked with ½ turn', 1),
('Lou Yun', 'E', 0.5, 'Double salto straddled with 1/1 t.', 1),
(NULL, 'E', 0.5, 'Salto bwd. str. with 1/1 t and salto bwd piked.', 1),
(NULL, 'E', 0.5, 'Double salto bwd. straigh', 1),
(NULL, 'E', 0.5, 'Double salto bwd. straigh with ½ t.', 1),
('Tamayo', 'E', 0.5, ' Arabian Jump bwd. to dbl. salto fwd. str.', 1),
(NULL, 'E', 0.5, 'Salto fwd. str. with 5/2 t.', 1),
('González', 'E', 0.5, 'Salto bwd. str. with 7/2 t', 1),
(NULL, 'F', 0.6, 'Double salto fwd. tucked with 1/1 turn.', 1),
('Zapata', 'F', 0.6, 'Double salto fwd. tucked with 3/2 turn.', 1),
(NULL, 'F', 0.6, 'Double salto bwd. tucked with 5/2 t.', 1),
('Kolyvanov', 'F', 0.6, 'Salto bwd. str. with 2/1 t and salto bwd piked.', 1),
('Penev', 'F', 0.6, 'Double salto bwd.straight with 1/1t', 1),
(NULL, 'F', 0.6, 'Arabian jump bwd. to dbl. salto fwd. str. with ½ t', 1),
('Shirai 2', 'F', 0.6, 'Salto fwd. str. with 3/1 t.', 1),
('Shirai / Nguyen', 'F', 0.6, 'Salto bwd. str. with 4/1 t.', 1),
('Zapata 2', 'G', 0.7, 'Double salto fwd. piked or straight with 3/2 turn.', 1),
('Ri Jong Song', 'G', 0.7, 'Double salto bwd. tucked with 3/1 t', 1),
(NULL, 'G', 0.7, 'Double salto bwd. str. with 3/2 t', 1),
('Hypolito', 'G', 0.7, 'Arabian Jump bwd. to dbl. salto fwd. str. with 1/1 t', 1),
(NULL, 'G', 0.7, 'Double salto bwd. str. with 2/1 t', 1),
('Goshima', 'G', 0.7, 'Salto fwd. str. with 7/2 t', 1),
(NULL, 'H', 0.8, 'Double salto str w 5/2 t.', 1),
('Minami', 'H', 0.8, 'Double salto bwd. tucked with 7/2 t.', 1),
('Liukin', 'I', 0.9, 'Triple salto bwd. tucked. ', 1),
('Shirai 3', 'I', 0.9, 'Double salto bwd. str. with 3/1 t', 1),
('Nagornyy', 'J', 1, 'Triple salto bwd. piked.', 1),
('Jarman', 'J', 1, 'Double salto bwd. str. with 7/2 t', 1),
--Mouvements pour le Cheval d'arçons
(NULL, 'A', 0.1, 'Scissor forward.', 2),
(NULL, 'A', 0.1, 'Scissor forward with ½ t.', 2),
(NULL, 'A', 0.1, 'Scissor backward.', 2),
(NULL, 'A', 0.1, 'Scissor backward with ½ turn.', 2),
(NULL, 'A', 0.1, 'Any circle or flair in side support.', 2),
(NULL, 'A', 0.1, 'Circles in cross support frontways on end.', 2),
(NULL, 'A', 0.1, 'Circles in cross support rearways on end.', 2),
(NULL, 'A', 0.1, 'Any ¼ spindle', 2),
(NULL, 'A', 0.1, 'Double rear (kehr).', 2),
(NULL, 'A', 0.1, 'Schwabenflank.', 2),
(NULL, 'A', 0.1, 'Wendeswing fwd. with ½ t. to support fwd. on the  end, from side support using 1 or 2 pommels.', 2),
(NULL, 'A', 0.1, 'Russian wendeswing with 180° or 270°.', 2),
(NULL, 'A', 0.1, 'Russian wendeswing with 360° or 540°.', 2),
(NULL, 'A', 0.1, 'On the leather, Russian wendeswing with 180°, or 270° also with travel.', 2),
(NULL, 'A', 0.1, 'On the leather, Russian wendeswing with 360° or 540°.', 2),
(NULL, 'A', 0.1, 'Circles with any travel in side support (1/3) (also with ¼ t.).', 2),
(NULL, 'A', 0.1, 'Travel bwd. in cross support from one horse part or pommel to another (⅓).', 2),
(NULL, 'A', 0.1, 'Wende from circle (also from Russian wendeswing 180° or 270°)', 2),
(NULL, 'A', 0.1, 'On the end, Russian wendeswing with 360° or 540°', 2),
(NULL, 'A', 0.1, 'From side support wendeswing fwd. with ½ t. to support followed by wende.', 2),
(NULL, 'B', 0.2, 'Scissor forward with travel sideways (also with 1/2 t.)', 2),
(NULL, 'B', 0.2, 'Double scissor fwd. (¼ t. fwd. a. ¼ t. bwd.).', 2),
(NULL, 'B', 0.2, 'Leg cut or undercut bwd. through handstand and lower to support with straddle legs.', 2),
(NULL, 'B', 0.2, 'Scissor bwd. with travel sideways (also with ½ t.).', 2),
(NULL, 'B', 0.2, 'Double scissor bwd. (¼ t. fwd. a. ¼ t. bwd).', 2),
(NULL, 'B', 0.2, 'Circle in side support outside pommels or between the pommels.', 2),
(NULL, 'B', 0.2, 'Circles in cross support on 1 pommel (from or to ¼ t. fwd.).', 2),
(NULL, 'B', 0.2, 'Circles in cross support between the pommels.', 2),
('Keikha 2', 'B', 0.2, 'Any ½ spindle', 2),
(NULL, 'B', 0.2, 'Direct Stöckli A (DSA) on the pommels or pommel between hands.', 2),
(NULL, 'B', 0.2, 'Direct Stöckli B (DSB).', 2),
(NULL, 'B', 0.2, 'Kehr with 270° t. on 1 p. (Sohn technique) from cross to side support.', 2),
(NULL, 'B', 0.2, 'Direct Tramlot.', 2),
(NULL, 'B', 0.2, 'Reverse Stöckli 180° (or 270° from one pommel) turn in one circle.', 2),
(NULL, 'B', 0.2, 'Czechkehre on the pommels or pommel between hands.', 2),
(NULL, 'B', 0.2, 'Russian wendeswing with 720° or 900°. ', 2),
(NULL, 'B', 0.2, 'On the leather, Russian wendeswing with 720° or 900°.', 2),
(NULL, 'B', 0.2, 'Russian wendeswing with 180° or 270° on 1 pommel or between the pommels.', 2),
(NULL, 'B', 0.2, 'Circles with any travel in side support (3/3).', 2),
(NULL, 'B', 0.2, 'Circles with any hop travel in side support (1/3)', 2),
(NULL, 'B', 0.2, 'Travel fwd. or bwd. with ¼ spindle to side support on 2 pommels.', 2),
(NULL, 'B', 0.2, 'Travel fwd. in cross support (1/2 or 2/3).', 2),
(NULL, 'B', 0.2, 'Travel bwd. in cross support (1/2 or 2/3).', 2),
(NULL, 'B', 0.2, 'Chaguinian to wende.', 2),
(NULL, 'B', 0.2, 'On the end, Russian wendeswing with 720° or 900°.', 2),
(NULL, 'B', 0.2, 'Circle or flair through handstand (also with ¾ t. with or without travel).', 2),
(NULL, 'C', 0.3, 'Scissor fwd. with hop sideways from one end to the other (3/3).', 2),
(NULL, 'C', 0.3, 'Double scissor fwd. (¼ t. fwd. a. ¼ t. bwd.) with travel sideways.', 2),
('Stepanyan', 'C', 0.3, 'Double Scissor fwd. with travel sideways through handstand.', 2),
(NULL, 'C', 0.3, 'Scissor bwd. with hop sideways from one end to the other (1-2 to 4-5). ', 2),
(NULL, 'C', 0.3, 'Swing bwd. w. ¼ t. through handstand on 1 pommel (also with ¼ t. after), lower to support with straddle legs (with legs changing)', 2),
('Tippelt', 'C', 0.3, 'Flair or circle through handstand (with or without ½ t.) and lower to flair or circle.', 2),
('Bertoncelj', 'C', 0.3, 'Kehr with 270° t. on 1 pommel (Sohn technique) from side to cross support.', 2),
('Davtyan', 'C', 0.3, 'Reverse Stöckli with 270° t. (Bezugo technique) from 2 pommels to cross support on 1 pommel', 2),
(NULL, 'C', 0.3, 'Russian wendeswing with 1080° or more.', 2),
(NULL, 'C', 0.3, 'On the leather, Russian wendeswing with 1080° or more.', 2),
(NULL, 'C', 0.3, 'Russian wendeswing with 360° or 540° on 1 pommel or between the pommels.', 2),
(NULL, 'C', 0.3, 'Any travel in side support (3/3), hands between pommels.', 2),
(NULL, 'C', 0.3, 'Circles with any hop travel 2x in side support (3/3).', 2),
(NULL, 'C', 0.3, 'All travels with ½ spindle in side support.', 2),
(NULL, 'C', 0.3, 'Travel fwd. in cross support with support on leather, pommel, pommel, leather (3/3) (1-2-4-5).', 2),
(NULL, 'C', 0.3, 'Travel bwd. in cross sup with support on leather, pommel, pommel, leather (3/3) (5-4-2-1).', 2),
(NULL, 'C', 0.3, 'From support on 1 pommel, Russian wendeswing fwd. to other end without support on or between the pommels (side to side support, side to cross support)', 2),
('Romero', 'C', 0.3, 'Reverse Stöckli from cross support on end to the far pommel', 2),
(NULL, 'C', 0.3, 'On the end, Russian wendeswing with 1080° or more.', 2),
(NULL, 'C', 0.3, 'DSA, reverse Stöckli or circle on one pommel through handstand.', 2),
(NULL, 'C', 0.3, 'Circle or flair with hop travel bwd. through handstand.', 2),
('Mikulak', 'D', 0.4, 'Double scissor forward sideways from one end to the other (3/3).', 2),
('Li Ning', 'D', 0.4, 'Scissor fwd. with ¼ t. through handstand on 1 pommel, lower to support with straddle legs on the other arm (with legs changing)', 2),
('Bryan', 'D', 0.4, 'Scissor fwd. with ¼ t. through handstand on 1 pommel, lower to support with straddle legs on the other arm (with legs changing)', 2),
(NULL, 'D', 0.4, 'Any side support pommel between hands 1/1 pindle w. legs straddle inside max. 2 circles.', 2),
('Magyar', 'D', 0.4, 'Any 1/1 spindle within max. 2 circles on the end.', 2),
('Keikha 3', 'D', 0.4, 'Direct Stöckli A (DSA) outside pommels', 2),
('Keikha 6', 'D', 0.4, 'Direct Stöckli A (DSA) outside pommels', 2),
(NULL, 'D', 0.4, 'Flair with hop travel bwd. through handstand and lower to circles or flairs', 2),
('Sohn', 'D', 0.4, 'Kehr with 1/1 turn on 1 pommel.', 2),
('Pinheiro', 'D', 0.4, 'Czechkehre outside pommels', 2),
(NULL, 'D', 0.4, '720° or 900° Russian wendeswing on 1 pommel or between the pommels.', 2),
(NULL, 'D', 0.4, 'Any travel in side support (3/3) over both pommels (also with hop).', 2),
('Nin Reyes', 'D', 0.4, 'Any travel fwd. 3/3 with ½ Spindle from one pommel over the other pommel.', 2),
('Titov', 'D', 0.4, 'Any travel fwd. 3/3 with ½ Spindle from one pommel over the other pommel.', 2),
('Magyar', 'D', 0.4, 'Any other travel fwd. in cross support to other end (3/3).', 2),
('Sivado', 'D', 0.4, 'Any other travel bwd. in cross support to other end (3/3).', 2),
('Moguilny', 'D', 0.4, 'Kehre fwd., reverse Stöckli, kehre fwd.', 2),
('Belenki', 'D', 0.4, 'Kehre bwd., kehre fwd., kehre bwd.', 2),
('Tong Fei', 'D', 0.4, 'From support on end, Russian wendeswing fwd. to other end without support on or between the pommels (side to side, side to cross, cross to side, cross to cross)', 2),
(NULL, 'D', 0.4, 'From support 1-2, 3/3 travel in Russian type wendeswing with 630° or more turning', 2),
('Roth', 'D', 0.4, 'Any Russian wendeswing with 360° t. and 3/3 travel', 2),
('Abu Alsoud', 'D', 0.4, 'Reverse Stöckli from cross support on one end to the other', 2),
('Kolyvanov', 'D', 0.4, 'From side support on end, circle or flair to handstand and travel 3/3 with 450° or more turn.', 2),
('Dolidze', 'D', 0.4, 'From pommels, circle with 1/4 turn to Russian wendeswing 270° on one pommel to handstand', 2),
('Jessen', 'D', 0.4, 'DSA with hop bwd. through handstand on other end.', 2),
('Loos', 'D', 0.4, 'DSA with hop bwd. through handstand on other end.', 2),
(NULL, 'D', 0.4, '180° Russian from one end of the horse to the other end through handstand to dismount', 2),
('Eichorn', 'E', 0.5, ' Any side support 1/1 spindle with hand support to the other side and return (max. 2 flairs or circles)', 2),
('Berki', 'E', 0.5, '1/1 spindle w. legs straddle or together on the pommels inside max. 2 circles.', 2),
('Bezugo', 'E', 0.5, 'Reverse Stöckli with 360° t. on 1 pommel.', 2),
(NULL, 'E', 0.5, '1080° Russian wendeswing or more on 1 pommel or between the pommels', 2),
('Yamawaki', 'E', 0.5, 'From side support beside the pommel, travel hop over 2 pommels to support fwd on other end (1-1 to 5-5).', 2),
(NULL, 'E', 0.5, 'From an end side travel with 2x ½ spindle  to other end.', 2),
('Nin Reyes 2', 'E', 0.5, 'Travel 3/3 over both pommels with ½ Spindle.', 2),
('Keikha 4', 'E', 0.5, 'Travel 3/3 over both pommels with ½ Spindle.', 2),
('Urzica 2', 'E', 0.5, 'Any 3/3 travel in flairs with 1/1 Spindle inside 2 circles.', 2),
('Burkhart', 'E', 0.5, 'Any 3/3 travel in flairs with 1/1 Spindle inside 2 circles.', 2),
('Driggs', 'E', 0.5, 'Travel forward in cross support over both pommels (also with hop).', 2),
('Kurbanov', 'E', 0.5, 'Travel backward in cross support over both pommels (also with hop).', 2),
('Reid', 'E', 0.5, 'Travel backward in cross support over both pommels (also with hop).', 2),
('Vammen', 'E', 0.5, 'On the leather, from cross support, Russian wendeswing with 360° or more over both pommels.', 2),
('Wu Guonian', 'E', 0.5, 'Any 3/3 travel in Russian type wendeswing with 720° or more turning w. two hands between pommels', 2),
(NULL, 'E', 0.5, 'DSA to handstand 3/3 with 450° or more turn.', 2),
('Keikha 1', 'F', 0.6, 'Any 1/1 spindle with both pommels between the hands (flair or circle).', 2),
('Keikha 5', 'F', 0.6, 'Any 1/1 spindle with both pommels between the hands (flair or circle).', 2),
(NULL, 'F', 0.6, 'Cross support, 1/1 spindle with hands between the pommels max. 2 circles.', 2),
('Busnari', 'F', 0.6, 'Reverse Stöckli, DSA or pommel circle straddle through handstand, 3/3 travel (fwd.- bwd), 360° turn to flairs', 2),
--Mouvements pour les anneaux
(NULL, 'A', 0.1, 'Uprise fwd. to support.', 3),
(NULL, 'A', 0.1, 'From any support scale, swallow or swing bwd in support, roll forward to bwd swing in hang.', 3),
(NULL, 'A', 0.1, 'From hang, felge upward to support.', 3),
(NULL, 'A', 0.1, 'Dislocate bwd. piked or straight.', 3),
(NULL, 'A', 0.1, 'Uprise bwd. to support.', 3),
(NULL, 'A', 0.1, 'Inlocate piked or straight.', 3),
(NULL, 'A', 0.1, 'Slow inlocate from hang.', 3),
(NULL, 'A', 0.1, 'Kip to support.', 3),
(NULL, 'A', 0.1, 'Back kip with bent arms to support.', 3),
(NULL, 'A', 0.1, 'Fwd. swing to swing bwd. in hang', 3),
(NULL, 'A', 0.1, 'From support or cross, felge bwd. piked or straight with bent arms to support.', 3),
(NULL, 'A', 0.1, 'L-sit (2 s.) or straddled L-sit (2 s.).', 3),
(NULL, 'A', 0.1, 'Hanging scale rearways (back lever) (2 s.).', 3),
(NULL, 'A', 0.1, 'Hanging scale frontways (front lever) (2 s.).', 3),
(NULL, 'A', 0.1, 'Support scale straddled (2 s.)', 3),
(NULL, 'A', 0.1, 'Press to hdst. with bent body and bent arms (2 s)', 3),
(NULL, 'A', 0.1, 'Slow roll fwd. piked with bent arms, to support', 3),
(NULL, 'A', 0.1, 'Salto fwd. piked or straight, also with ½ t.', 3),
(NULL, 'A', 0.1, 'Salto bwd. piked or straight also with ½.', 3),
('Chechi', 'B', 0.2, 'Uprise fwd and counter salto fwd. to bwd swing in hang.', 3),
(NULL, 'B', 0.2, 'Swing fwd. through hdst', 3),
(NULL, 'B', 0.2, 'Uprise bwd. str. through handstand.', 3),
('Honma', 'B', 0.2, 'Backward swing to salto fwd. piked to support', 3),
('Yamawaki', 'B', 0.2, 'Double salto fwd. tucked to hang. ', 3),
(NULL, 'B', 0.2, 'Back kip to support.', 3),
(NULL, 'B', 0.2, 'Back kip or roll bwd str. with bent arms to handstand (2 s.).', 3),
(NULL, 'B', 0.2, 'From support swing bwd. to handstand (2 s.).', 3),
(NULL, 'B', 0.2, 'V-sit (2 s.).', 3),
(NULL, 'B', 0.2, 'Press to hdst. with str. body a. bent arms or b. body. a. str. arms, or fr. strad. sup. lever (2 s.).', 3),
(NULL, 'B', 0.2, 'Slow roll fwd. straight with bent arms, to support.', 3),
(NULL, 'B', 0.2, 'Slow roll bwd. slowly and straight. body to L sit (2 s.).', 3),
(NULL, 'B', 0.2, 'Vertical pull up with bent arms to hanging scale rearways (2 s.).', 3),
(NULL, 'B', 0.2, 'Fr. cross or L-cr., move fwd. to back lever (2 s.). ', 3),
(NULL, 'B', 0.2, 'From hdst., lower horiz. to back lever (2 s.).', 3),
(NULL, 'B', 0.2, 'From handstand, lower slowly through inverted cross to inverted hang.', 3),
(NULL, 'B', 0.2, 'Uprise fwd. to L-sit, (2 s.)', 3),
(NULL, 'B', 0.2, 'Kip to L-sit (2 s.).', 3),
(NULL, 'B', 0.2, 'Honma to L-sit (2 s.).', 3),
('Delchev', 'B', 0.2, 'Felge upward to support with straddled legs supported above the rings (2 s.).', 3),
(NULL, 'B', 0.2, 'Felge upward to support scale straddled (2 s.)', 3),
(NULL, 'B', 0.2, 'Uprise bwd. to support scale straddled (2 s.).', 3),
(NULL, 'B', 0.2, 'Salto fwd. piked or straight with 1/1 t', 3),
(NULL, 'B', 0.2, 'Salto bwd. straight with 1/1 t', 3),
(NULL, 'B', 0.2, 'Double salto bwd. tucked or piked', 3),
('Guczoghy', 'C', 0.3, 'Tucked double salto bwd. to hang', 3),
(NULL, 'C', 0.3, 'Honma straight.', 3),
('Jonasson', 'C', 0.3, 'Double salto fwd. piked or straight to hang.', 3),
(NULL, 'C', 0.3, 'Bwd. swing, salto piked to support', 3),
(NULL, 'C', 0.3, 'Swing fwd. to handstand or giant swing bwd to handstand (2 s.).', 3),
(NULL, 'C', 0.3, 'Uprise bwd. to handstand or giant swing fwd to handstand  (2 s.).', 3),
(NULL, 'C', 0.3, 'Honma and swing bwd. to handstand (2 s.).', 3),
(NULL, 'C', 0.3, 'Support scale (planche)(2 s.).', 3),
(NULL, 'C', 0.3, 'Any cross (2 s.)or V cross (2 s.)', 3),
(NULL, 'C', 0.3, 'Press to hdst. with str. body and str. arms from support or support scale (2 s.)', 3),
(NULL, 'C', 0.3, 'Slow roll fwd. straight to cross or L-cross (2 s.)', 3),
(NULL, 'C', 0.3, 'Vertical pull up with straight arms to hanging scale rearways (2 s.).', 3),
(NULL, 'C', 0.3, 'Vertical pull up to L-sit (2 s.).', 3),
('Li Xiaoshuang', 'C', 0.3, 'From sup. or cross, lower slowly to hang, and pull with str. arms to cross (2 s.).', 3),
(NULL, 'C', 0.3, 'From cross or L-cross, press to L-sit (2 s.).', 3),
(NULL, 'C', 0.3, 'Uprise fwd. to V-sit (2 s.)', 3),
(NULL, 'C', 0.3, 'Kip to V-sit (2 s.).', 3),
('Gracia', 'C', 0.3, 'Homna to V-sit  (2 s.).', 3),
(NULL, 'C', 0.3, 'Uprise fwd. to cross or L-cross (2 s.).', 3),
(NULL, 'C', 0.3, 'Uprise bwd. to cross or L-cross (2 s.).', 3),
(NULL, 'C', 0.3, 'Kip to cross, or L-cross (2 s.).', 3),
(NULL, 'C', 0.3, 'Back kip to cross or L-cross (2 s.).', 3),
(NULL, 'C', 0.3, 'Felge upward to cross or L-cross (2 s.).', 3),
(NULL, 'C', 0.3, 'Salto fwd. piked or straight with 3/2 t.', 3),
(NULL, 'C', 0.3, 'Double salto fwd. tucked or tucked with ½ t.', 3),
(NULL, 'C', 0.3, 'Salto bwd. straight with 2/1 t. or 3/2 t.', 3),
(NULL, 'C', 0.3, 'Double salto bwd. straight.', 3),
(NULL, 'C', 0.3, 'Double salto bwd. t. with ½ or 1/1 t.', 3),
(NULL, 'C', 0.3, 'Double salto bwd. t. with 3/2 t.', 3),
(NULL, 'C', 0.3, 'Salto bwd. str. with 1/1 t. and salto t.', 3),
(NULL, 'D', 0.4, 'Piked or straight double salto bwd. to hang.', 3),
(NULL, 'D', 0.4, 'Honma str. and swing bwd. to handstand (2 s.).', 3),
(NULL, 'D', 0.4, 'Inverted cross (2 s.)', 3),
('Hirondelle', 'D', 0.4, 'Support scale at ring height (swallow or maltese cross) (2 s.).', 3),
('Tsukahara 3', 'D', 0.4, 'V Cross, press to V-sit (2 sec.).', 3),
(NULL, 'D', 0.4, 'Press to hdst. with str. body and str. arms from swallow (2 s.).', 3),
('Azarian', 'D', 0.4, 'Slow Roll bwd. with straight body to cross, Lcross or V cross (2 s.).', 3),
('Nakayama', 'D', 0.4, 'From or through hanging scale rearways pull to cross, L-cross, or V cross (2 s.).', 3),
(NULL, 'D', 0.4, 'Vertical pull up to cross or L-cross (2 s.).', 3),
(NULL, 'D', 0.4, 'From swallow, press to support scale (2 s.).', 3),
(NULL, 'D', 0.4, 'From cross, press to planche without first going to support (2 s.).', 3),
('Vorobiov/Zou', 'D', 0.4, 'From inverted cross lower slowly to inverted hang and felge bwd. slowly to cross (2 s.)', 3),
('Ng Kiu Chung 2', 'D', 0.4, 'Slow roll fwd. with straight body through cross and press to support scale without first going to support (2 s.).', 3),
('Davtyan', 'D', 0.4, 'Slow roll fwd. with str. body to Cross or L-Cross (2 s.), also from inverted hang.', 3),
('Cingolani', 'D', 0.4, 'From hang vertical pull up support and press to hdst. with straight body and straight arms.', 3),
(NULL, 'D', 0.4, 'Honma to cross / L-cross (2 s.).', 3),
(NULL, 'D', 0.4, 'Bwd. swing, salto fwd p. to cross or L-cross (2 s.).', 3),
('Molinari', 'D', 0.4, 'Kip to V cross (2 s.).', 3),
(NULL, 'D', 0.4, 'Back kip to support scale (2 s.).', 3),
(NULL, 'D', 0.4, 'Felge upward to support scale (2 s.).', 3),
(NULL, 'D', 0.4, 'Uprise bwd. to support scale (2 s.).', 3),
(NULL, 'D', 0.4, 'Felge bwd. straight to free sup. scale. (2 s.)', 3),
(NULL, 'D', 0.4, 'Salto fwd. piked or straight with 2/1 t.', 3),
('Fischer', 'D', 0.4, 'Double salto fwd. tucked with 3/2 t (also 1/1 t.)', 3),
('Balabanov', 'D', 0.4, 'Double salto fwd. piked or piked with ½ t.', 3),
(NULL, 'D', 0.4, 'Double salto bwd. straight with ½ or 1/1 t.', 3),
(NULL, 'E', 0.5, 'Inverted swallow (2 s.).', 3),
('Colak', 'E', 0.5, 'Vertical pull up with str. arms to V-cross (2 s.)', 3),
('Van Gelder', 'E', 0.5, 'From planche, lower horiz. and slowly to hanging scale rw. and press to swallow (2 s.) or from swallow same to planche or planche to planche.', 3),
(NULL, 'E', 0.5, 'From swallow, lower slowly to hanging scale, press to swallow (2 s.).', 3),
(NULL, 'E', 0.5, 'From L-cross, press to inverted cross (2 s.).', 3),
(NULL, 'E', 0.5, 'From cross, press to swallow (2 s.).', 3),
('Jotchev', 'E', 0.5, 'From inverted cross lower slowly to inverted hang and felge bwd. slowly to swallow (2 s.) or to support scale (2 s.) ', 3),
('Yan Mijayoung', 'E', 0.5, 'Roll bwd. slowly with str. arms and body to free sup. scale (2 s.).', 3),
(NULL, 'E', 0.5, 'Slow Roll bwd. with str. body to swallow (2 s.)', 3),
('Wynn', 'E', 0.5, 'Slow roll fwd. with straight body through cross to inverted cross (2 s.).', 3),
('Pham 2', 'E', 0.5, 'Slow roll forward with straight body through cross to swallow (2 sec).', 3),
('Balandin 3', 'E', 0.5, 'From hang vertical pull up thr. swallow to sup. scale (2 s.).', 3),
('Tanaka', 'E', 0.5, 'Honma to V cross (2 s.).', 3),
(NULL, 'E', 0.5, 'Back kip to swallow (2 s.).', 3),
(NULL, 'E', 0.5, 'Back kip to inverted cross (2 s.).', 3),
(NULL, 'E', 0.5, 'Felge upward to Swallow (2 s.).', 3),
(NULL, 'E', 0.5, 'Felge upward to invert. cross (2 s.).', 3),
(NULL, 'E', 0.5, 'Uprise bwd. to sup. scale at ring height (2 s.).', 3),
(NULL, 'E', 0.5, 'Uprise bwd. to inverted cross (2 s.).', 3),
(NULL, 'E', 0.5, 'Double salto fwd. piked with 3/2 t. (also 1/1 t.).', 3),
(NULL, 'E', 0.5, 'Salto bwd. straight with 3/1 t.', 3),
(NULL, 'E', 0.5, 'Double salto bwd. t. with 2/1 t.', 3),
('Zahran', 'F', 0.6, 'Through hanging scale rearways pull with str. body through cross to inv. swallow (2 s.).', 3),
('Zanetti', 'F', 0.6, 'From hanging scale rw. press to swallow (also to Support Scale) (2 s.).', 3),
(NULL, 'F', 0.6, 'From cross, press with straight body to inverted cross (2 s.).', 3),
(NULL, 'F', 0.6, 'From swallow, press to inverted cross (2 s.).', 3),
('Simonov', 'F', 0.6, 'Roll backward slowly with straight arms and body to inverted cross through swallow.', 3),
('Tulloch', 'F', 0.6, 'Azarian to inverted Swallow (2 s.).', 3),
('Balandin 1', 'F', 0.6, 'From hang vertical pull up to swallow (2 s.).', 3),
(NULL, 'F', 0.6, 'Kip to inverted swallow (2 s.).', 3),
('Rodrigues', 'F', 0.6, 'Uprise forward to inverted swallow (2 s.).', 3),
('Tuuha', 'F', 0.6, 'Double salto bwd. t. with 5/2 t.', 3),
(NULL, 'F', 0.6, 'Double salto bwd. straight with 3/2 or 2/1 t.', 3),
('Tulloch 2', 'G', 0.7, 'From hang vertical pull up, slowly with straight arms through cross to inverted swallow (2 s.).', 3),
('Carmona', 'G', 0.7, 'Through hang rearways press and straight body to inverted cross (2 s.)', 3),
('Balandin 2', 'G', 0.7, 'From hang vertical pull up to inv. cross (2 s.).', 3),
(NULL, 'G', 0.7, 'Triple salto bwd. tucked.', 3),
('Whittenburg', 'I', 0.9, 'Triple salto bwd. piked.', 3),
---Mouvements pour le Saut de cheval
(NULL, NULL, 1.2, 'Forward handspring.', 4),
(NULL, NULL, 1.2, 'Handspring sw. with ¼ t.', 4),
(NULL, NULL, 1.2, 'Round off, handspring bwd.', 4),
(NULL, NULL, 1.4, 'Forward handspring with ½ t.', 4),
(NULL, NULL, 1.4, 'Handspring sw. with 3/4 t.', 4),
(NULL, NULL, 1.4, 'Round off, handspring bwd. with ½ turn.', 4),
(NULL, NULL, 1.4, 'Round off, ½ t. and handspring fwd.', 4),
(NULL, NULL, 1.6, 'Forward handspring with 1/1 t.', 4),
(NULL, NULL, 1.6, 'Handspring sw. with 5/4 t.', 4),
(NULL, NULL, 1.6, 'Round off, handspring bwd. with 1/1 turn.', 4),
(NULL, NULL, 1.6, 'Round off, ½ t. and hdspr. fwd. with ½ t.', 4),
(NULL, NULL, 1.8, 'Forward handspring with 3/2 t.', 4),
('Tsukahara', NULL, 1.8, 'Handspring sw. w. ¼ t. a. salto bwd. t.', 4),
('Yurchenko', NULL, 1.8, 'Round off, hdspr. bwd. and salto bwd. t.', 4),
(NULL, NULL, 1.8, 'Round off, ½ t. and hdspr. fwd. with 1/1 t.', 4),
(NULL, NULL, 2.0, 'Forward handspring with 2/1 t.', 4),
(NULL, NULL, 2.0, 'Handspring fwd. and salto fwd. tucked.', 4),
(NULL, NULL, 2.0, 'Tsukahara piked.', 4),
(NULL, NULL, 2.0, 'Tsukahara t. with ½ t.', 4),
(NULL, NULL, 2.0, 'Yurchenko t. with ½ t.', 4),
(NULL, NULL, 2.0, 'Yurchenko piked.', 4),
('Tsygankov', NULL, 2.2, 'Forward handspring with 5/2 t.', 4),
(NULL, NULL, 2.2, 'Round off, ½ t. and hdspr. fwd. and salto fwd. tucked.', 4),
(NULL, NULL, 2.4, 'Hdspr. fwd. and salto fwd. t. w. ½ t. (or Cuervo t.)', 4),
('Kasamatsu', NULL, 2.4, 'Hdspr. sw. w. ¼ t. a. salto fwd. t. w. ½ t. or Tsuk. t. w. 1/1 t', 4),
(NULL, NULL, 2.4, 'Handspring fwd. and salto fwd. piked.', 4),
(NULL, NULL, 2.4, 'Yurchenko t. with 1/1 t.', 4),
(NULL, NULL, 2.6, 'Round off, ½ t. and hdspr. fwd. and salto fwd. tucked with ½ t.', 4),
(NULL, NULL, 2.6, 'Round off, ½ t. a. hdspr. fwd. and salto fwd. p.', 4),
(NULL, NULL, 2.8, ' Hdspr. fwd. and salto fwd. t. w. 1/1 t. (Cuervo t. w. ½ t.).', 4),
(NULL, NULL, 2.8, 'Hdspr. fwd. and salto fwd. p. w. ½ t. (Cuervo p.).', 4),
(NULL, NULL, 2.8, 'sukahara t. w. 3/2 t.or Kasamatsu t. ½ t', 4),
(NULL, NULL, 2.8, 'Tsukahara straight.', 4),
(NULL, NULL, 2.8, 'Yurchenko t. with 3/2 t.', 4),
(NULL, NULL, 2.8, 'Yurchenko straight.', 4),
('Nemov', NULL, 3.0, 'Round off, ½ t. and hdspr. fwd. and salto fwd. p. with ½ t.', 4),
('Kroll', NULL, 3.2, 'Hdspr. fwd. and salto fwd. t. w. 3/2 t. (Cuervo t. w. 1/1 t.).', 4),
(NULL, NULL, 3.2, 'Hdspr. fwd. and salto fwd. p. w. 1/1 t. (Cuervo p. w. ½ t.).', 4),
('Barbieri', NULL, 3.2, 'Tsukahara t. with 2/1 t.', 4),
(NULL, NULL, 3.2, 'Handspring fwd. and salto fwd. str.', 4),
(NULL, NULL, 3.2, 'Tsukahara str. with ½ t', 4),
(NULL, NULL, 3.2, 'Yurchenko t. with 2/1 t.', 4),
(NULL, NULL, 3.2, 'Yurchenko straight with ½ t.', 4),
(NULL, NULL, 3.4, 'Round off, ½ t. and hdspr. fwd. and salto fwd. str.', 4),
('Canbas', NULL, 3.6, 'Hdspr. fwd. and salto fwd. t. w. 2/1 t. (or Cuervo t. w. 3/2 t.).', 4),
(NULL, NULL, 3.6, 'Hdspr. fwd. and salto fwd. p. w. 3/2 t. (Cuervo p. w. 1/1 t.).', 4),
(NULL, NULL, 3.6, 'Hdspr. fwd. and salto fwd. str. w. ½ t. (Cuervo str.).', 4),
(NULL, NULL, 3.6, 'Tsukahara t. with 5/2 t.', 4),
(NULL, NULL, 3.6, 'Tsukahara str. w. 1/1 t. or Kasamatsu str.', 4),
(NULL, NULL, 3.6, 'Yurchenko straight with 1/1 t.', 4),
('Hutcheon', NULL, 3.8, 'Round off, ½ t. and hdspr. fwd. and salto fwd. str. with ½ t.', 4),
(NULL, NULL, 4.0, 'Hdspr. fwd. and salto fwd. str. w. 1/1 t. (Cuervo str. ½ t.).', 4),
(NULL, NULL, 4.0, 'Kasamatsu str. with ½ t. or Tsukahara str. w. 3/2 t.', 4),
(NULL, NULL, 4.0, 'Yurchenko straight with 3/2 t.', 4),
(NULL, NULL, 4.2, 'Round off, ½ t. and hdspr. fwd. and salto fwd. str. with 1/1 t.', 4),
('Lou-Yun', NULL, 4.4, 'Hdspr. fwd. and salto fwd. str. w. 3/2 t. (Cuervo str. w. 1/1 t.).', 4),
('Akopian', NULL, 4.4, 'Kasamatsu str. w. 1/1 t. or Tsukahara str. w. 2/1 t', 4),
(NULL, NULL, 4.4, 'Yurchenko straight with 2/1 t.', 4),
(NULL, NULL, 4.6, 'Round off, ½ t. and hdspr. fwd. and salto fwd. straight with 3/2 t.', 4),
(NULL, NULL, 4.8, 'Hdspr. fwd. and salto fwd. str. w. 2/1 t. (Cuervo str. 3/2 t.).', 4),
('Driggs', NULL, 4.8, 'Kasamatsu str. with 3/2 t.', 4),
('Roche', NULL, 4.8, 'Handspring fwd. and dbl. salto fwd. t.', 4),
('Yeo', NULL, 4.8, 'Tsukahara with salto bwd. t.', 4),
('Shewfelt', NULL, 4.8, 'Yurchenko straight with 5/2 t.', 4),
('Melissanidis', NULL, 4.8, 'Yurchenko and salto bwd. tucked.', 4),
(NULL, NULL, 5.0, 'Round off, ½ t. and hdspr. fwd. and salto fwd. straight with 2/1 t.', 4),
(NULL, NULL, 5.0, 'Round off, ½ t. a. hdspr. fwd. and double salto fwd. tucked.', 4),
('Yeo 2', NULL, 5.2, 'Handspring fwd. and salto fwd. str. w. 5/2 t.', 4),
('López', NULL, 5.2, 'Kasamatsu str. with 2/1 t.', 4),
('Dragulescu', NULL, 5.2, 'Roche with ½ turn.', 4),
('Zimmerman', NULL, 5.2, 'Handspring fwd. and salto fwd. t. w. ½ t. and salto bwd. t.', 4),
('Blanik', NULL, 5.2, 'Handspring fwd. and dbl. salto fwd. piked.', 4),
('Lu Yu Fu', NULL, 5.2, 'Tsukahara with salto bwd. piked.', 4),
('Shirai - KIM Hee Hoon', NULL, 5.2, ' Yurchenko Straight 3/1 t.', 4),
('Yang Wei', NULL, 5.2, ' Melissanidis piked.', 4),
('Li Xiao Peng', NULL, 5.4, 'Round off, ½ t. and hdspr. fwd. and salto fwd. str. with 5/2 t.', 4),
('Yang Hak Seon', NULL, 5.6, 'Handspring fwd. and salto fwd. str. w. 3/1 t.', 4),
('Yonekura', NULL, 5.6, 'Kasamatsu str. with 5/2 t. or Tsukahara str. with 7/2 t.', 4),
('RI Se Gwang 2', NULL, 5.6, 'Dragulescu piked', 4),
('Ri Se Gwang', NULL, 5.6, 'Double Tsukahara with 1/1 twist.', 4),
('Shirai 2', NULL, 5.6, 'Yurchenko Straight 7/2 t.', 4),
---Mouvements pour les Barres parallèles
(NULL, 'A', 0.1, 'Forward uprise to support.', 5),
(NULL, 'A', 0.1, 'Fwd. uprise with ¼ t. to hang on 1 rail.', 5),
(NULL, 'A', 0.1, 'Bwd. uprise and straddled cut or flank over to support.', 5),
(NULL, 'A', 0.1, 'Any swing to handstand', 5),
(NULL, 'A', 0.1, 'Any L-sit on 1 or 2 rails (2 s.)', 5),
(NULL, 'A', 0.1, 'Straddle cut bwd. to support.', 5),
(NULL, 'A', 0.1, 'Straddle cut fwd. to support or L-sit (2 s.).', 5),
(NULL, 'A', 0.1, 'Healy to upper arm hang (also from handstand on 1 rail).', 5),
(NULL, 'A', 0.1, 'Any handstand . with ½ turn. (also with 2 s.)', 5),
(NULL, 'A', 0.1, 'Glide kip.', 5),
(NULL, 'A', 0.1, 'Cast to upper arm hang.', 5),
(NULL, 'A', 0.1, 'Felge with travel to hang', 5),
(NULL, 'A', 0.1, 'Felge forward to support.', 5),
(NULL, 'A', 0.1, 'Salto fwd. piked or straight also with ½ t.', 5),
(NULL, 'A', 0.1, 'Salto bwd. piked or straight, also with ½ t.', 5),
(NULL, 'A', 0.1, 'From hang on end, salto bwd. straight.', 5),
(NULL, 'B', 0.2, 'Fwd. uprise and straddle cut bwd to handstand.', 5),
('Watanabe', 'B', 0.2, 'Roll bwd. with ½ t. from upper arm hang or Fwd. uprise to Kato hop to support.', 5),
(NULL, 'B', 0.2, 'Roll bwd. to handstand with straight arms.', 5),
(NULL, 'B', 0.2, 'Salto bwd. with straddled. cut to upper arm hang.', 5),
(NULL, 'B', 0.2, 'Bwd. uprise to handstand (or with ½ t).', 5),
(NULL, 'B', 0.2, 'Bwd. uprise with ½ t. and straddle cut bwd. to upper arm hang.', 5),
(NULL, 'B', 0.2, 'Bwd. uprise with ½ t. to support.', 5),
(NULL, 'B', 0.2, 'Bwd. uprise and straddled cut or flank over to support straight. arm.', 5),
('Kato', 'B', 0.2, 'Bent arm swing fwd. to hop ½ t. to support.', 5),
(NULL, 'B', 0.2, 'Any press with bent arm straight. body, or str. arm bent body to handstand., on 1 or 2 rails (2 s.) also straddled', 5),
(NULL, 'B', 0.2, 'Straddle cut bwd. to handstand.', 5),
('Carminucci', 'B', 0.2, 'Swing fwd. with 1/1 t. to upper arm hang.', 5),
('Carballo', 'B', 0.2, 'Swing fwd. to handstand, hop to support.', 5),
(NULL, 'B', 0.2, 'Handstand. with ¼ t. and fall back to support with ¼ t.', 5),
(NULL, 'B', 0.2, 'Stützkehr bwd. to support.', 5),
(NULL, 'B', 0.2, 'Following a swing element (min. B) to handstand on 1 rail, Healy to upper arm hang.', 5),
(NULL, 'B', 0.2, 'From handstand on 1 rail, ½ or ¾ t. fwd. or bwd. In handstand.', 5),
(NULL, 'B', 0.2, 'Any 1/1 pirouette in handstand on 2 rails', 5),
(NULL, 'B', 0.2, '5/4 salto fwd. tuck or pike to upper arm hang', 5),
(NULL, 'B', 0.2, 'Moy piked with straddled. cut bwd. and ½ t. to upper arm hang (also legs together).', 5),
(NULL, 'B', 0.2, 'Moy to support bent legs (also without grip release)', 5),
(NULL, 'B', 0.2, 'Swing down with salto bwd. straight to hang', 5),
(NULL, 'B', 0.2, 'Giant swing bwd. with straddled cut to upperaddledarm hang', 5),
(NULL, 'B', 0.2, 'Glide kip with ½ t. to support.', 5),
(NULL, 'B', 0.2, 'Glide kip to straddled cut bwd. handstand on 1 or 2 rail.', 5),
(NULL, 'B', 0.2, 'Glide kip one rail through L-sit straddled to handstand.', 5),
('Li Donghua', 'B', 0.2, 'Glide kip through V-sit and hop ½ turn to hang on other rail.', 5),
(NULL, 'B', 0.2, 'Cast to support', 5),
(NULL, 'B', 0.2, 'Cast with ½ t. to up. arm hang.', 5),
(NULL, 'B', 0.2, 'Felge to support', 5),
('Gagnon', 'B', 0.2, 'Felge roll backward with tuck salto ½ to upper arm hang.', 5),
(NULL, 'B', 0.2, 'Felge forward with ½ t. to support.', 5),
(NULL, 'B', 0.2, 'Salto fwd. piked or straight with 1/1', 5),
(NULL, 'B', 0.2, 'Double salto bwd. tuck from end.', 5),
('Muntean', 'C', 0.3, 'Fwd. uprise and straddle cut bwd to hang.', 5),
('Kovtun', 'C', 0.3, 'Back toss from upper arm with 1/4 turn to one rail', 5),
(NULL, 'C', 0.3, 'Roll bwd. with straddled cut to support.', 5),
(NULL, 'C', 0.3, 'Bwd. uprise with ½ t. hop to handstand.', 5),
(NULL, 'C', 0.3, 'Bwd. uprise with ½ t. a. straddled cut bwd. to support.', 5),
('Yamawaki', 'C', 0.3, 'Bwd. uprise and 5/4 salto fwd. t. to upper arm hang', 5),
(NULL, 'C', 0.3, 'Stützkehr fwd. to handstand (to 1 or 2 bars).', 5),
('Salazar', 'C', 0.3, 'Diamidov and ½ turn to upper arms.', 5),
('Babos', 'C', 0.3, 'Straddle cut bwd. directly to hang', 5),
('Diamidov', 'C', 0.3, 'Swing fwd. with 1/1 t. on 1 arm to handstand.', 5),
(NULL, 'C', 0.3, 'Makuts to upper arm hang or ¾ Diamidov ¼ Healy to support.', 5),
(NULL, 'C', 0.3, 'Salto bwd to handstand. Also to one rail.', 5),
('Toumilovich', 'C', 0.3, 'Salto bwd. with ½ t. to upper arm hang', 5),
('Brändström', 'C', 0.3, 'Handstand . with ¾ t. and fall back to support with ¼ t.', 5),
('Novikov', 'C', 0.3, 'Stützkehr bwd. through handstand. to support.', 5),
(NULL, 'C', 0.3, 'Stützkehr bwd. with straddle cut bwd. to support', 5),
('Healy', 'C', 0.3, 'Healy to support (also from handstand on 1 rail).', 5),
(NULL, 'C', 0.3, 'Swing bwd. with ½ t. hop to handstand.', 5),
('Carballo 2', 'C', 0.3, '  From handstand, salto fwd to support or from handstand with rotated grip, inlocate to support.', 5),
(NULL, 'C', 0.3, 'Salto fwd to support.', 5),
('Juarez 2', 'C', 0.3, 'Salto fwd. piked to hang.', 5),
(NULL, 'C', 0.3, '5/4 salto fwd. straight to upper arm hang', 5),
('Alsadi', 'C', 0.3, 'Swing forward, straddle cut backward, and regrasp with straight body at horizontal to bent and upper arm.', 5),
('Nolet', 'C', 0.3, 'Moy piked with 1/1 t. to upper arm hang.', 5),
('Moy', 'C', 0.3, 'Moy to support straddled legs (also without grip release).', 5),
('Kenmotsu', 'C', 0.3, 'Giant swing bwd. to handstand or with inlocation fwd. (also with ¼ or ½ turn and to one rail).', 5),
('Wells', 'C', 0.3, 'Giant swing bwd. to handstand or with inlocation fwd. (also with ¼ or ½ turn and to one rail).', 5),
('Gushiken', 'C', 0.3, 'Giant swing bwd. with ½ t. to upper arm hang.', 5),
('Chartrand', 'C', 0.3, 'Giant swing bwd. and salto with ½ t. to hang on the end.', 5),
(NULL, 'C', 0.3, 'Glide kip bwd. to handstand.', 5),
('Okubo', 'C', 0.3, 'Glide kip to straddled cut bwd. to hand.', 5),
(NULL, 'C', 0.3, 'Glide kip through L-sit piked to handstand.', 5),
(NULL, 'C', 0.3, 'Felge with ½ t. to upper arm hang.', 5),
(NULL, 'C', 0.3, 'Cast with ½ t. to support.', 5),
('Arican', 'C', 0.3, 'Cast to straddle cut backward to handstand.', 5),
(NULL, 'C', 0.3, 'Felge with immediate straddle cut to support', 5),
('Gagnon 2', 'C', 0.3, 'Felge roll backward with straight salto ½ to upper arm hang.', 5),
(NULL, 'C', 0.3, 'Salto fwd. piked or straight. 3/2 t.', 5),
(NULL, 'C', 0.3, 'Double salto fwd. tuck from end.', 5),
(NULL, 'C', 0.3, 'Salto bwd. piked or straight with 1/1 or 3/2 t.', 5),
(NULL, 'C', 0.3, 'Double salto bwd. tuck', 5),
(NULL, 'C', 0.3, 'From hang on end, double salto bwd. Tuck.', 5),
('Harada', 'D', 0.4, 'Roll bwd. with ½ t. tuck to upper arm hang.', 5),
(NULL, 'D', 0.4, 'Bwd. uprise with ¾ t. hop to handstand on 1 rail.', 5),
(NULL, 'D', 0.4, 'Bwd. uprise and salto fwd. pike or straight to support', 5),
('Bilozerchev - Peters', 'D', 0.4, 'Stützkehr fwd. to handstand (1 rail (also with additional ¼ or ¾ turn to handstand)', 5),
('Dimic', 'D', 0.4, 'Stützkehr fwd. to handstand (1 rail (also with additional ¼ or ¾ turn to handstand)', 5),
('De Freitas', 'D', 0.4, '¾ Diamidov and rear vault to side hang on 1 bar.', 5)